apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: fluent-bit
    meta.helm.sh/release-namespace: fluentbit
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 2.2.1
    helm.sh/chart: fluent-bit-0.42.0
  name: fluent-bit
  namespace: fluentbit
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
  - name: http
    port: 2020
    protocol: TCP
    targetPort: http
  - name: otel
    port: 4318
    protocol: TCP
    targetPort: otel
  - name: otelhttp
    port: 4317
    protocol: TCP
    targetPort: otelhttp
  - name: prom
    port: 2021
    targetPort: prom
  selector:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/name: fluent-bit
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fluentbit-monitor
  labels:
    app.kubernetes.io/instance: fluent-bit
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: fluent-bit
  namespaceSelector:
    matchNames:
      - fluentbit
  endpoints:
    - port: prom
      interval: 15s

