apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-sidecar
spec:
  mode: sidecar
  hostNetwork: true
  env:
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  image: otel/opentelemetry-collector-contrib-dev:latest
  config: |
    receivers:
      opencensus:
        endpoint: 0.0.0.0:55678
    
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
        send_batch_max_size: 1000
        timeout: 30s
        send_batch_size : 800

      memory_limiter:
         check_interval: 1s
         limit_percentage: 70
         spike_limit_percentage: 30



    exporters:
     

      otlphttp:
        endpoint: http://fluent-bit.fluentbit.svc.cluster.local:4318
        compression: none
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp,opencensus]
          processors: [memory_limiter,batch]
          exporters: [otlphttp]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter,batch]
          exporters: [otlphttp]
        logs:
          receivers: [otlp]
          processors: [memory_limiter,batch]
          exporters: [otlphttp]